# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'MiaoLive' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  pod 'Masonry', '~> 1.0.1'
  pod 'MBProgressHUD', '~> 1.0.0'
  pod 'MJRefresh', '~> 3.1.12'
  pod 'AFNetworking', '~> 3.1.0'
  pod 'XRCarouselView', '~> 2.5.5'
  pod 'SDWebImage', '~> 3.8.1'
  pod 'BarrageRenderer', '~> 1.9.0'
  # Pods for MiaoLive
	

end
